### PR TITLE
Display error message when unauthorized

### LINKED ISSUE #128: Extract generic Next.js API handler
Currently we have to check `request.method` in some API endpoints in order to distinguish between fetching an entity or deleting/updating it. Instead, we could have a shared handler that takes a map and uses the right handler for the request method. 

Something like this:
```javascript
import {StatusCodes, ReasonPhrases} from 'http-status-codes';

export const commonHandler = (handlers) => (request, response) => {
    const handler = handlers[request.method.toLowerCase()];

    if (!handler) {
        return response
           .status(StatusCodes.METHOD_NOT_ALLOWED)
            .json({error: ReasonPhrases.METHOD_NOT_ALLOWED});
    }

    return handler(request, response);
}
```

That would be used like this:
```javascript
export default commonHandler({
    "get": (req, res) => {},
    "patch": (req, res) =. {}
})
```

### LINKED ISSUE #155: Display unauthorized errors in the error toast notification
Right now a 403 from Rode will have the same error notification as a 500, but it would be helpful if it rendered a different message

https://github.com/rode/rode-ui/pull/142#pullrequestreview-701274535

### PR DESCRIPTION
**Pull request by alexashley**
Closes #155 
Closes #128 

- added a wrapper around the Next.js api routes to handle known methods and exceptions
- updated the api utils to prepend the Rode API url, since it's the only service in use.
- all Next.js api endpints will proxy the Rode status code in case of an error
- any actions on the front end that aren't covered under the anonymous role should display a toast message:

Screen Shot 2021-07-22 at 4 06 33 PM

### CODE REVIEW

**Comment by RobertKelly** [comment]
Like it!

File: components/policies/PolicyForm.js [hunk 1]
```diff
@@ -102,6 +104,11 @@ const PolicyForm = ({
 
     setLoading(false);
 
+    if (response.status === StatusCodes.FORBIDDEN) {
```
Comment (alexashley) [inline components/policies/PolicyForm.js:107]: Opened an issue to address the redundancy of these checks: https://github.com/rode/rode-ui/issues/165

**Review by mrparkers — APPROVED** [review]
tested this locally in a few places and everything works the way I expect it to.

LGTM, nice work!
